-- Create initial database
CREATE DATABASE expenses
WITH  OWNER = postgres

-- Create expenses table

CREATE TABLE expenses  (
    id INT,
    name VARCHAR(255),
    price VARCHAR(255),
    sku VARCHAR(255),
    dateadded timestamp,
    lastupdate timestamp
)

-- Update id to become primary key
ALTER TABLE expenses ADD primary key (id INT)

-- Update price to be numberic type
ALTER TABLE expenses 
ALTER COLUMN price TYPE NUMERIC USING price::numeric;

-- Use timestampz for timezones
ALTER TABLE expenses
ALTER COLUMN dateadded TYPE timestamptz;

ALTER TABLE expenses
ALTER COLUMN lastupdate TYPE timestamptz;

-- Auto add incrementing Primary Key (ID)
ALTER TABLE expenses 
ALTER id ADD GENERATED BY DEFAULT AS IDENTITY;