-- Create initial database
CREATE DATABASE expenses WITH  OWNER = postgres

-- Create expenses table

CREATE TABLE expenses  (
    id INT,
    name VARCHAR(255),
    price VARCHAR(255),
    sku VARCHAR(255),
    dateadded timestamp,
    lastupdate timestamp
)

-- Update id to become primary key
ALTER TABLE expenses ADD primary key (id)

-- Update price to be numberic type
ALTER TABLE expenses 
ALTER COLUMN price TYPE NUMERIC USING price::numeric;

-- Use timestampz for timezones
ALTER TABLE expenses
ALTER COLUMN dateadded TYPE timestamptz;

ALTER TABLE expenses
ALTER COLUMN lastupdate TYPE timestamptz;

-- Auto add incrementing Primary Key (ID)
ALTER TABLE expenses 
ALTER id ADD GENERATED BY DEFAULT AS IDENTITY;


-- Create budget table
CREATE TABLE budget  (
    id SERIAL PRIMARY KEY,
    budget NUMERIC,
    dateadded timestamptz,
    lastupdate timestamptz
)

-- Add authentication table
CREATE TABLE users(
  pk SERIAL PRIMARY KEY,
  id UUID,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  UNIQUE(id)
);


-- Drop NOT NULL on id
ALTER TABLE users ALTER COLUMN id NOT NULL

-- Generate random id for id column
ALTER TABLE users
ALTER COLUMN id SET DEFAULT gen_random_uuid()

-- Add uuid on budget
ALTER TABLE budget
ADD COLUMN uuid VARCHAR(255) NOT NULL

-- Add uuid on expenses
ALTER TABLE expenses
ADD COLUMN uuid VARCHAR(255) NOT NULL
