# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: create .env file
      run: |
        touch .env
        echo DB_host=${{ secrets.DB_HOST }} > .env
        echo DB_port=${{ secrets.DB_PORT }} >> .env
        echo DB_user=${{ secrets.DB_USER }} >> .env
        echo DB_password=${{ secrets.DB_PASSWORD }} >> .env
        echo DB_name=${{ secrets.DB_NAME }} >> .env
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.26.2'

    - name: Build
      run: go build -v ./...

    - name: Set up Postgres
      run: go run ./scripts/db-migrate.go
      env:
        # Values used to init db in db-migrate.go
        ACTIONS_DB_host: "${{ secrets.DB_HOST }}
        ACTIONS_DB_port: ${{ secrets.DB_PORT }}
        ACTIONS_DB_user: ${{ secrets.DB_USER }}
        ACTIONS_DB_pw: ${{ secrets.DB_PASSWORD }
        ACTIONS_DB_name: ${{ secrets.DB_NAME }}


    - name: Test
      run: go test -v ./...
